---
spring:
  application:
    name: eureka-client
  profiles: peer1
server:
  port: 8003
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server-peer1:8761/eureka/,http://eureka-server-peer2:8762/eureka/,http://eureka-server-peer3:8763/eureka/

---
spring:
  application:
    name: eureka-client
  profiles: peer2
server:
  port: 8004
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server-peer1:8761/eureka/,http://eureka-server-peer2:8762/eureka/,http://eureka-server-peer3:8763/eureka/
