---
spring:
  application:
    name: eureka-consumer-ribbon-hystrix
  profiles: peer1
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
server:
  port: 7001
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server-peer1:8761/eureka/,http://eureka-server-peer2:8762/eureka/,http://eureka-server-peer3:8763/eureka/
---
spring:
  application:
    name: eureka-consumer-ribbon-hystrix
  profiles: peer2
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
server:
  port: 7002
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server-peer1:8761/eureka/,http://eureka-server-peer2:8762/eureka/,http://eureka-server-peer3:8763/eureka/
