spring:
  application:
    name: turbine-amqp
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
server:
  port: 8989
management:
  port: 8990
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server-peer1:8761/eureka/,http://eureka-server-peer2:8762/eureka/